[project]
name = "moviedb"
version = "1.0.1"
description = "Movie database app."
dependencies = [
    "flask",
    "flask-login",
    "flask-sqlalchemy",
    "pillow"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = [
  "."
]

[tool.coverage.run]
branch = true
source = ["moviedb"]
